// catchAsync es una función de utilidad para envolver los controladores de ruta y capturar errores asíncronos.
const catchAsync = (fn) => {
    return (req, res, next) => {
        // Ejecuta la función del controlador y pasa cualquier error al siguiente middleware.
        fn(req, res, next).catch(next);
    };
};

export default catchAsync;

